[package]
name = "test_client"
version = "0.1.0"
authors = ["Robin Appelman <robin@icewind.nl>"]
edition = "2018"

[dependencies]
tungstenite = { version = "0.19.0", features = ["rustls-tls-webpki-roots"] }
serde_json = "1.0.99"
ureq = "2.7.1"
flexi_logger = { version = "0.25.5", features = ["colors"] }
log = "0.4.19"
base64 = "0.21.2"
miette = { version = "5.10.0", features = ["fancy"] }
url = "2.4.0"
